/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package BeastBot;

/**
 *
 * @author simpl
 */
public class CallibrateOnClickFrame extends javax.swing.JFrame {

    /**
     * Creates new form CallibrateOnClickFrame
     * 
     * @param clicker transfer settings to the clicker
     * @param i index of the key
     */
    public CallibrateOnClickFrame(Clicker clicker, int i) {
        initComponents();
        this.clicker = clicker;
        this.targetKeyIndex = i;
        fullScreen();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setAlwaysOnTop(true);
        setUndecorated(true);
        setResizable(false);
        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                updateXYCoordinates(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void updateXYCoordinates(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_updateXYCoordinates
        clicker.buttonCoords[targetKeyIndex] = getMousePosition();
        dispose();
    }//GEN-LAST:event_updateXYCoordinates

    private void fullScreen() {
        setSize(getToolkit().getScreenSize().width, getToolkit().getScreenSize().height);
        setLocation(0, 0);
        setOpacity((float) 0.5);
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables

    private Clicker clicker;
    private int targetKeyIndex;
}
