/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package BeastBot;

import javax.swing.ComboBoxModel;
import javax.swing.event.ListDataListener;

/**
 *
 * @author simpl
 */
public class ConfigurationFrame extends javax.swing.JFrame {

    /**
     * Creates new form ConfigurationFrame
     *
     * @param clicker transfer setting to the clicker
     */
    public ConfigurationFrame(Clicker clicker) {
        initComponents();
        this.clicker = clicker;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ImportButton = new javax.swing.JButton();
        ExportButton = new javax.swing.JButton();
        CancelButton = new javax.swing.JButton();
        OKButton = new javax.swing.JButton();
        NumberOfKeysLable = new javax.swing.JLabel();
        NumberOfKeysSpinner = new javax.swing.JSpinner();
        KeysComboBox = new javax.swing.JComboBox<>();
        KeyCoordinatesLable = new javax.swing.JLabel();
        xCoordinateLable = new javax.swing.JLabel();
        xCoordinateSpinner = new javax.swing.JSpinner();
        CallibrateOnClickButton = new javax.swing.JButton();
        CoordinatesSectionSeparator = new javax.swing.JSeparator();
        yCoordinateLable = new javax.swing.JLabel();
        yCoordinateSpinner = new javax.swing.JSpinner();
        UpDateCoordinatesButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setAlwaysOnTop(true);
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                selecetDefaultNumberOfKeys(evt);
            }
        });

        ImportButton.setFont(new java.awt.Font("Dialog", 0, 10)); // NOI18N
        ImportButton.setText("Import");
        ImportButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ImportButtonActionPerformed(evt);
            }
        });

        ExportButton.setFont(new java.awt.Font("Dialog", 0, 10)); // NOI18N
        ExportButton.setText("Export");

        CancelButton.setFont(new java.awt.Font("Dialog", 0, 10)); // NOI18N
        CancelButton.setText("Cancel");
        CancelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CancelButtonActionPerformed(evt);
            }
        });

        OKButton.setFont(new java.awt.Font("Dialog", 0, 10)); // NOI18N
        OKButton.setText("OK");

        NumberOfKeysLable.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        NumberOfKeysLable.setText("Number of Keys");

        NumberOfKeysSpinner.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        NumberOfKeysSpinner.setModel(new javax.swing.SpinnerNumberModel(4, 1, 10, 1));
        NumberOfKeysSpinner.setToolTipText("");
        NumberOfKeysSpinner.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                updateNumberOfKeys(evt);
            }
        });

        KeysComboBox.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        KeysComboBox.setMaximumRowCount(10);
        KeysComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Key 1", "Key 2", "Key 3", "Key 4" }));
        KeysComboBox.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                keySelected(evt);
            }
        });
        KeysComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                KeysComboBoxActionPerformed(evt);
            }
        });

        KeyCoordinatesLable.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        KeyCoordinatesLable.setText("Key Coordinates");

        xCoordinateLable.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        xCoordinateLable.setText("x-coordinate");

        xCoordinateSpinner.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        xCoordinateSpinner.setModel(new javax.swing.SpinnerNumberModel(0, 0, null, 1));
        xCoordinateSpinner.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                updateXCoordinate(evt);
            }
        });

        CallibrateOnClickButton.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        CallibrateOnClickButton.setText("Callibrate on Click");
        CallibrateOnClickButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CallibrateOnClickButtonActionPerformed(evt);
            }
        });

        yCoordinateLable.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        yCoordinateLable.setText("y-coordinate");

        yCoordinateSpinner.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        yCoordinateSpinner.setModel(new javax.swing.SpinnerNumberModel(0, 0, null, 1));
        yCoordinateSpinner.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                updateYCoordinate(evt);
            }
        });

        UpDateCoordinatesButton.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        UpDateCoordinatesButton.setText("Update Coordinates");
        UpDateCoordinatesButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UpDateCoordinatesButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(CoordinatesSectionSeparator)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(NumberOfKeysLable)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(NumberOfKeysSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(KeyCoordinatesLable)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(KeysComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(CallibrateOnClickButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(UpDateCoordinatesButton)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(ImportButton)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(ExportButton)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 162, Short.MAX_VALUE)
                                    .addComponent(OKButton)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(xCoordinateLable)
                                    .addGap(196, 196, 196)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(yCoordinateLable)
                                .addGap(196, 196, 196)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(yCoordinateSpinner)
                            .addComponent(xCoordinateSpinner)
                            .addComponent(CancelButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(NumberOfKeysLable)
                    .addComponent(NumberOfKeysSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(CoordinatesSectionSeparator, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(KeyCoordinatesLable)
                    .addComponent(KeysComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CallibrateOnClickButton)
                    .addComponent(UpDateCoordinatesButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(xCoordinateLable)
                    .addComponent(xCoordinateSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(yCoordinateLable)
                    .addComponent(yCoordinateSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ImportButton)
                    .addComponent(ExportButton)
                    .addComponent(OKButton)
                    .addComponent(CancelButton))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ImportButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ImportButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ImportButtonActionPerformed

    private void CancelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CancelButtonActionPerformed
        dispose();
    }//GEN-LAST:event_CancelButtonActionPerformed

    private void KeysComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_KeysComboBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_KeysComboBoxActionPerformed

    private void updateNumberOfKeys(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_updateNumberOfKeys
        int n = (int) NumberOfKeysSpinner.getModel().getValue();
        clicker.setKeyN(n);
        KeysComboBoxModel keysComboBoxModel = new KeysComboBoxModel(n);
        KeysComboBox.setModel(keysComboBoxModel);
        KeysComboBox.setSelectedItem("Key 1");
    }//GEN-LAST:event_updateNumberOfKeys

    private void CallibrateOnClickButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CallibrateOnClickButtonActionPerformed
        int i = KeysComboBox.getSelectedIndex();
        java.awt.EventQueue.invokeLater(() -> {
            new CallibrateOnClickFrame(clicker, i).setVisible(true);
        });
    }//GEN-LAST:event_CallibrateOnClickButtonActionPerformed

    private void keySelected(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_keySelected
        int i = KeysComboBox.getSelectedIndex();
        xCoordinateSpinner.setValue(clicker.buttonCoords[i].x);
        yCoordinateSpinner.setValue(clicker.buttonCoords[i].y);
    }//GEN-LAST:event_keySelected

    private void updateXCoordinate(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_updateXCoordinate
        int i = KeysComboBox.getSelectedIndex();
        clicker.buttonCoords[i].x = (int) xCoordinateSpinner.getValue();
    }//GEN-LAST:event_updateXCoordinate

    private void updateYCoordinate(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_updateYCoordinate
        int i = KeysComboBox.getSelectedIndex();
        clicker.buttonCoords[i].y = (int) yCoordinateSpinner.getValue();
    }//GEN-LAST:event_updateYCoordinate

    private void UpDateCoordinatesButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UpDateCoordinatesButtonActionPerformed
        keySelected(null);
    }//GEN-LAST:event_UpDateCoordinatesButtonActionPerformed

    private void selecetDefaultNumberOfKeys(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_selecetDefaultNumberOfKeys
        int n = (int) NumberOfKeysSpinner.getModel().getValue();
        System.out.println(n);
        clicker.setKeyN(n);
    }//GEN-LAST:event_selecetDefaultNumberOfKeys

//    /**
//     * @param args the command line arguments
//     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(ConfigurationFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(ConfigurationFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(ConfigurationFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(ConfigurationFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new ConfigurationFrame().setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton CallibrateOnClickButton;
    private javax.swing.JButton CancelButton;
    private javax.swing.JSeparator CoordinatesSectionSeparator;
    private javax.swing.JButton ExportButton;
    private javax.swing.JButton ImportButton;
    private javax.swing.JLabel KeyCoordinatesLable;
    private javax.swing.JComboBox<String> KeysComboBox;
    private javax.swing.JLabel NumberOfKeysLable;
    private javax.swing.JSpinner NumberOfKeysSpinner;
    private javax.swing.JButton OKButton;
    private javax.swing.JButton UpDateCoordinatesButton;
    private javax.swing.JLabel xCoordinateLable;
    private javax.swing.JSpinner xCoordinateSpinner;
    private javax.swing.JLabel yCoordinateLable;
    private javax.swing.JSpinner yCoordinateSpinner;
    // End of variables declaration//GEN-END:variables

    private Clicker clicker;

    class KeysComboBoxModel implements ComboBoxModel<String> {

        /**
         *
         * @param n number of keys will be displayed in the combo box
         */
        public KeysComboBoxModel(int n) {
            keyNames = new String[n];
            for (int i = 0; i < keyNames.length; i++) {
                keyNames[i] = new StringBuffer().append("Key ").append(i + 1).toString();
            }
            selection = null;
            listDataListener = null;
        }

        @Override
        public void setSelectedItem(Object anItem) {
            selection = (String) anItem;
        }

        @Override
        public Object getSelectedItem() {
            return selection;
        }

        @Override
        public int getSize() {
            return keyNames.length;
        }

        @Override
        public String getElementAt(int index) {
            return keyNames[index];
        }

        @Override
        public void addListDataListener(ListDataListener l) {
            listDataListener = l;
        }

        @Override
        public void removeListDataListener(ListDataListener l) {
            listDataListener = null;
        }

        private String[] keyNames;
        private String selection;
        private ListDataListener listDataListener;
    }
}
